@mainUrl = http://localhost:3000/task

###
#
GET {{mainUrl}}/get-all
Content-Type: application/json

###
#
POST {{mainUrl}}/add
Content-Type: application/json

{
    "title": "Test 16"
}

###
#
DELETE {{mainUrl}}/delete
Content-Type: application/json

{
    "id": "1"
}


###
#
PUT {{mainUrl}}/update-title
Content-Type: application/json

{
    "id": "1",
    "newTitle": "Changed Title"
}