services:
  app:
    build:
      context: ./app
      dockerfile: ../.docker/app/Dockerfile
    container_name: app.taskproject2
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  api:
    build:
      context: ./api
      dockerfile: ../.docker/api/Dockerfile
    container_name: api.taskproject2
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    working_dir: /app
    environment:
      NODE_ENV: development

  mysql:
    image: mysql:8.4.8
    container_name: mysql.taskproject2
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: task
      MYSQL_USER: task
      MYSQL_PASSWORD: task
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: pma.taskproject2
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: task
      PMA_PASSWORD: task

volumes:
  mysql_data: