services:
  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    container_name: api.taskproject2
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: app.taskproject2
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

  mysql:
    image: mysql:8.0.32
    container_name: mysql.taskproject2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proiectan
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - proiectan_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: pma.taskproject2
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8088:80"
    depends_on:
      - mysql

volumes:
  proiectan_mysql_data:
